const db=window.supabase.createClient("https://bimttawmwzuzlbzgpbqo.supabase.co","sb_publishable_TTQQPHcHGI_a_47m3k_ujg_AN0MpqDA");
let cart=JSON.parse(localStorage.getItem("luvexa_lightting_cart")||"[]");
const count=document.getElementById("cartCount"),cm=document.getElementById("cartModal"),items=document.getElementById("cartItems"),ct=document.getElementById("cartTotal");
function render(){count.textContent=cart.reduce((s,x)=>s+x.q,0);let t=0;items.innerHTML=cart.length?cart.map((x,i)=>{t+=x.p*x.q;return `<div class="cart-item"><span>${x.n}<br>${x.p} TND × ${x.q}</span><span><button onclick="chg(${i},-1)">−</button> <button onclick="chg(${i},1)">+</button></span></div>`}).join(""):"<p>Votre panier est vide.</p>";ct.textContent=t+" TND";localStorage.setItem("lUVEXA_LIGHTING_cart",JSON.stringify(cart))}
window.chg=(i,d)=>{cart[i].q+=d;if(cart[i].q<1)cart.splice(i,1);render()};
document.querySelectorAll(".order-btn").forEach(b=>b.onclick=e=>{e.preventDefault();openOrder(b.dataset.product,Number(b.dataset.price),1)});
document.getElementById("cartLink").onclick=e=>{e.preventDefault();render();cm.hidden=false};document.getElementById("closeCart").onclick=()=>cm.hidden=true;
document.querySelectorAll(".order-btn").forEach(b=>{});
function openOrder(n,p,q){product.value=n;price.value=p;quantity.value=q;selectedProduct.textContent=n+" — "+p+" TND";orderTotal.textContent=(p*q)+" TND";orderMessage.textContent="";orderModal.hidden=false}
const orderModal=document.getElementById("orderModal"),product=document.getElementById("product"),price=document.getElementById("price"),quantity=document.getElementById("quantity"),selectedProduct=document.getElementById("selectedProduct"),orderTotal=document.getElementById("orderTotal"),orderMessage=document.getElementById("orderMessage");
document.getElementById("closeOrder").onclick=()=>orderModal.hidden=true;quantity.oninput=()=>orderTotal.textContent=(Number(price.value)*Math.max(1,Number(quantity.value)))+" TND";
document.getElementById("cartCheckout").onclick=()=>{if(!cart.length)return;let n=cart.map(x=>x.n+" × "+x.q).join(", "),t=cart.reduce((s,x)=>s+x.p*x.q,0);cm.hidden=true;openOrder(n,t,1)};
document.getElementById("orderForm").onsubmit=async e=>{e.preventDefault();orderMessage.textContent="Enregistrement…";let q=Math.max(1,Number(quantity.value)),p=Number(price.value),g=document.getElementById("governorate").value.trim(),a=document.getElementById("address").value.trim(),n=document.getElementById("notes").value.trim();let r=await db.from("orders").insert([{customer_name:customer_name.value.trim(),phone:phone.value.trim(),address:a+" — "+g+(n?" — Note: "+n:""),products:[{name:product.value,quantity:q,unit_price:p}],total:Number((p*q).toFixed(2)),status:"pending"}]);if(r.error)orderMessage.textContent="Erreur lors de l'envoi.";else{orderMessage.textContent="Commande confirmée avec succès ✓";cart=[];render()}};
render();
